#!/bin/bash
API=https://api.iextrading.com/1.0
if [ -z "$1" ] 
then
echo usage ./stock ticker
else
RESULT="$(curl -s $API/stock/$1/quote?displayPercent=true | jq .changePercent,.latestPrice )"
echo "% $RESULT"
fi
