#!/bin/bash

result=$(curl -ss https://www.google.com/finance?q=NYSE%3A$1 | awk '/priceChangePercent/{getline;print}' | sed -e 's/content=\"/ /' -e 's/"\ \/>/%/')
if [ -z "$result" ]
then 
	echo "Stock Not Found"
else 
echo $result
fi
